# Drone CI File!

kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: builds

node_selector:
  doks.digitalocean.com/node-pool: josa-cloud-np

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: josaorg/dsp-web
      build_args: 
        [
          DSP_API_URL=https://dsp.api.prod.josa.ngo,
          MATOMO_SITE_ID=3,
          TARGET_ENV=production
        ]
      build_args_from_env:
        [
          DRONE_BUILD_NUMBER,
          DRONE_BUILD_LINK,
          DRONE_COMMIT_SHA,
          DRONE_COMMIT_LINK,
          DRONE_REPO_LINK,
          DRONE_BUILD_FINISHED,
        ]
      tags:
        - ${DRONE_COMMIT_SHA}
        - stable
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: heartbeat
    depends_on:
      - build
